name: Deploy FTP para HostGator

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Instalar Dependências e Gerar Build
      run: |
        npm install
        npm run build

    - name: Enviar Arquivos via FTP Nativo
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -c "
        set ftp:ssl-allow no;
        open -u ${{ secrets.FTP_USERNAME }},'${{ secrets.FTP_PASSWORD }}' ${{ secrets.FTP_SERVER }};
        mirror -R --delete ./dist/ ./;
        quit;
        "
